site_name: Admin Guide
plugins:
  - search
extra_css:
  - stylesheets/custom.css
theme:
  name: material
  logo: assets/giframework-maps-icon.svg
  favicon: assets/giframework-maps-icon.svg
  features:
    - navigation.instant
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to system preference
markdown_extensions:
- toc:
    permalink: true
- tables
- attr_list
- admonition
- md_in_html
- pymdownx.details
- pymdownx.superfences
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/Dorset-Council-UK/GIFramework-Maps
copyright: All content is available under the Open Government Licence v3.0 except where otherwise stated
nav:
    - Home: 'index.md'
    - 'Administration via the management interface':
        - 'Getting started': 'gui/getting-started.md'
        - 'Atttributions': 'gui/attributions.md'
        - 'Bounds': 'gui/bounds.md'
        - 'Broadcast': 'gui/broadcast.md'
        - 'Layers': 'gui/layers.md'
        - 'Search definitions': 'gui/search-definitions.md'
        - 'System': 'gui/system.md'
        - 'Themes': 'gui/themes.md'
        - 'Tours': 'gui/tours.md'
        - 'Users': 'gui/users.md'
        - 'Versions': 'gui/versions.md'
        - 'Welcome messages': 'gui/welcome-messages.md'
    - 'Administration via the database (advanced)':
        - 'Getting started': 'db/getting-started.md'
        - 'Admin roles': 'db/admin-roles.md'
        - 'Analytics Definitions': 'db/analytics-definitions.md'
        - 'Attributions': 'db/attributions.md'
        - 'Basemaps': 'db/basemaps.md'
        - 'Bounds': 'db/bounds.md'
        - 'Categories': 'db/categories.md'
        - 'Layers': 'db/layers.md'
        - 'Print Configuration': 'db/print-config.md'
        - 'Projections': 'db/projections.md'
        - 'Proxying': 'db/proxy.md'
        - 'Search Definitions': 'db/search-definitions.md'
        - 'Theming': 'db/theming.md'
        - 'Tours': 'db/tours.md'
        - 'Versions': 'db/versions.md'
        - 'Web Service Definitions': 'db/web-service-definitions.md'
        - 'Welcome Messages': 'db/welcome-messages.md'
        - 'Clearing the cache': 'db/clear-cache.md'
